### DISCUSSION TITLE
Make port and protocol configurable

### DISCUSSION THREAD

**Discussion by ocso** [nagyrobi/home-assistant-custom-components-pfsense-gateways#9] [Ideas]
The current version works only with http on default 80 port.
Sensor.py contains the following url format: 
`DEFAULT_RESOURCE = "http://{0}/status_gateways_json.php?key={1}"`

Ii would be nice if protocol and port can be configured from HA sensor yaml, like:

```
sensor:
- platform: pfsense_gateways
  host: 192.168.1.1
  port: 9500
  ssl: true
  name: pfSense gateway
  key: pfsense
  monitored_gateway_interfaces:
    - wan
    - opt2
```

**Comment by nagyrobi** [comment]
Ssl would not work with self-signed certificates, only trusted ones...

**Reply by ocso** [reply]
Hi, I make the desired changes in my local HA installation and works fine with custom ports and self-signed certificate.

```
sensor:
- platform: pfsense_gateways
  host: 192.168.1.1
  port: 9500
  protocol: https
  name: pfSense gateway
  key: pfsense
  monitored_gateway_interfaces:
    - wan
```

`DEFAULT_RESOURCE = "{0}://{1}:{2}/status_gateways_json.php?key={3}"`

**Reply by nagyrobi** [reply]
Submit a PR, then!

**Reply by ocso** [reply]
Ok, I am going to prepare the PR, it was just a manual change with hardcoded values in the sensor.py

**Reply by ocso** [reply]
I have just realized that use use `CONF_RESOURCE`, so I can override the url template for pfsense in the sensor configuration by adding custom "resource" parameter:

```
- platform: pfsense_gateways
  host: 192.168.1.1
  name: pfSense gateway
  key: 'pfsense'
  resource: "https://{0}:5555/status_gateways_json.php?key={1}"
  monitored_gateway_interfaces:
    - wan
```

So no changes is required. Thanks!
