### ISSUE TITLE
Make port and protocol configurable

### ISSUE THREAD

**Issue by ocso** [nagyrobi/home-assistant-custom-components-pfsense-gateways#8]
The current version works only with http on default 80 port.
Sensor.py contains the following url format: 
`DEFAULT_RESOURCE = "http://{0}/status_gateways_json.php?key={1}"`

Ii would be nice if protocol and port can be configured from HA sensor yaml, like:

```
sensor:
- platform: pfsense_gateways
  host: 192.168.1.1
  port: 9500
  ssl: true
  name: pfSense gateway
  key: pfsense
  monitored_gateway_interfaces:
    - wan
    - opt2
```
